language: ruby
rvm:
- 2.3.3
before_script:
 - chmod +x cibuild.sh
script: cibuild.sh
deploy: 
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  on:
    branch: master